### ISSUE TITLE
建议增加一个 配置文档  自己可以去修改配置参数  例如命名格式

### ISSUE THREAD

**Issue by lbcake** [raindrop-hb/douyin_spider#3]
建议增加一个 配置文档  自己可以去修改配置参数  例如命名格式

["author"]["nickname"] ["aweme_id"] 等标签参数   支持自己可修改模式 还有python的格式化时间  也支持一下 自己可修改 

%y 两位数的年份表示（00-99）

%Y 四位数的年份表示（000-9999）

%m 月份（01-12）

%d 月内中的一天（0-31）

%H 24小时制小时数（0-23）

%I 12小时制小时数（01-12）

%M 分钟数（00=59）

%S 秒（00-59）

%a 本地简化星期名称

%A 本地完整星期名称

%b 本地简化的月份名称

%B 本地完整的月份名称

%c 本地相应的日期表示和时间表示

%j 年内的一天（001-366）

%p 本地A.M.或P.M.的等价符

%U 一年中的星期数（00-53）星期天为星期的开始

%w 星期（0-6），星期天为星期的开始

%W 一年中的星期数（00-53）星期一为星期的开始

%x 本地相应的日期表示

%X 本地相应的时间表示

%Z 当前时区的名称

%% %号本身

下面列出一些格式化字符串及其含义：
%Y-%m-%d：年-月-日
%H:%M:%S：时:分:秒
%Y-%m-%d %H:%M:%S：年-月-日 时:分:秒
%Y%m%d%H%M%S：年月日时分秒
%A, %B %d %Y：星期全称，月份全称 日 年
%Y-%m-%d %H:%M:%S.%f：年-月-日 时:分:秒.毫秒

('%Y-%m-%d %H:%M:%S')    '2022-05-31 09:08:18'
('%Y-%m-%d %H:%M:%S.%f')    '2022-05-31 09:08:18.428828'

**Comment by raindrop-hb** [comment]
![image](https://github.com/raindrop-hb/douyin_spider/assets/72308008/38e65b9f-16dd-41ee-a312-e97fa5aa9511)
