### ISSUE TITLE
作者主页链接 多种格式支持

### ISSUE THREAD

**Issue by lbcake** [raindrop-hb/douyin_spider#4]
长连接目前不支持啊  都支持一下

**Comment by raindrop-hb** [comment]
什么长链接

**Comment by lbcake** [comment]
> 什么长链接

https://www.douyin.com/user/MS4wLjABAAAAfEaPTLkHbsNlmGO9_llWqpZpQ6lZw1816Nz8IvdAczfHvJStsLY1DOgsYRJk0K6Q
 这种的不支持啊  只能app端链接

**Comment by raindrop-hb** [comment]
已更
